package frc.robot.subsystems.Elevator;

import org.littletonrobotics.junction.LogTable;
import org.littletonrobotics.junction.inputs.LoggableInputs;

// Raymond: this class is generated by @AutoLog at build time - you don't hand-write or check it in.
// delete the file and let the annotation make it (that's the whole point of the @AutoLog on
// ElevatorIOInputs). a hand-rolled copy will drift from the real fields, which is already happening
// - see `connected` below.
public class ElevatorIOInputsAutoLogged extends ElevatorIO.ElevatorIOInputs
    implements LoggableInputs, Cloneable {

  @Override
  public void toLog(LogTable table) {

    table.put("elevatorMotorVolts", elevatorMotorVolts);
    table.put("elevatorMotorCurrent", elevatorMotorCurrent);

    table.put("elevatorPositionMeters", elevatorPositionMeters);
    table.put("elevatorVelocityMetersPerSec", elevatorVelocityMetersPerSec);

    table.put("atTop", atTop);
    table.put("atBottom", atBottom);
    // Raymond: `connected` exists on the inputs and Real sets it, but you never log/restore/clone
    // it here - so it's invisible in logs and lost on replay. another reason to just let @AutoLog
    // generate this.
  }

  @Override
  public void fromLog(LogTable table) {

    elevatorMotorVolts = table.get("elevatorMotorVolts", elevatorMotorVolts);

    elevatorMotorCurrent = table.get("elevatorMotorCurrent", elevatorMotorCurrent);

    elevatorPositionMeters = table.get("elevatorPositionMeters", elevatorPositionMeters);

    elevatorVelocityMetersPerSec =
        table.get("elevatorVelocityMetersPerSec", elevatorVelocityMetersPerSec);

    atTop = table.get("atTop", atTop);
    atBottom = table.get("atBottom", atBottom);
  }

  @Override
  public ElevatorIOInputsAutoLogged clone() {
    ElevatorIOInputsAutoLogged copy = new ElevatorIOInputsAutoLogged();

    copy.elevatorMotorVolts = elevatorMotorVolts;
    copy.elevatorMotorCurrent = elevatorMotorCurrent;

    copy.elevatorPositionMeters = elevatorPositionMeters;
    copy.elevatorVelocityMetersPerSec = elevatorVelocityMetersPerSec;

    copy.atTop = atTop;
    copy.atBottom = atBottom;

    return copy;
  }
}
