// Raymond: this whole file is generated by the @AutoLog annotation on ClimberIOInputs - you
// normally don't hand-write or commit it (it lands in build/). if you're keeping it, fine, but then
// Climber.java MUST actually use this class as its inputs field, which it doesn't. right now you
// wrote the AutoLogged class and then never used it.
package frc.robot.subsystems.climber;

import org.littletonrobotics.junction.LogTable;
import org.littletonrobotics.junction.inputs.LoggableInputs;

public class ClimberIOInputsAutoLogged extends ClimberIO.ClimberIOInputs implements LoggableInputs, Cloneable {

  @Override
  public void toLog(LogTable table) {
    table.put("HookOutputCurrent", hookOutputCurrent);
    table.put("HookOutputVoltage", hookOutputVoltage);
    table.put("HookPositionDeg", hookPositionDeg);
    table.put("HookVelocity_dps", hookVelocity_dps);

    table.put("WheelOutputCurrent", wheelOutputCurrent);
    table.put("WheelOutputVoltage", wheelOutputVoltage);
    table.put("WheelPositionDeg", wheelPositionDeg);
    table.put("WheelVelocity_dps", wheelVelocity_dps);
  }

  @Override
  public void fromLog(LogTable table) {
    hookOutputCurrent = table.get("HookOutputCurrent", hookOutputCurrent);
    hookOutputVoltage = table.get("HookOutputVoltage", hookOutputVoltage);
    hookPositionDeg = table.get("HookPositionDeg", hookPositionDeg);
    hookVelocity_dps = table.get("HookVelocity_dps", hookVelocity_dps);

    wheelOutputCurrent = table.get("WheelOutputCurrent", wheelOutputCurrent);
    wheelOutputVoltage = table.get("WheelOutputVoltage", wheelOutputVoltage);
    wheelPositionDeg = table.get("WheelPositionDeg", wheelPositionDeg);
    wheelVelocity_dps = table.get("WheelVelocity_dps", wheelVelocity_dps);
  }

  @Override
  public ClimberIOInputsAutoLogged clone() {
    ClimberIOInputsAutoLogged copy = new ClimberIOInputsAutoLogged();

    copy.hookOutputCurrent = hookOutputCurrent;
    copy.hookOutputVoltage = hookOutputVoltage;
    copy.hookPositionDeg = hookPositionDeg;
    copy.hookVelocity_dps = hookVelocity_dps;

    copy.wheelOutputCurrent = wheelOutputCurrent;
    copy.wheelOutputVoltage = wheelOutputVoltage;
    copy.wheelPositionDeg = wheelPositionDeg;
    copy.wheelVelocity_dps = wheelVelocity_dps;

    return copy;
  }
}
